package com.rbc.util;

public class EmailInlineText {

    private EmailInlineText(){
    }

    //Return HTML Page code in String
    public static String emailInlineHTMLText() {

        return "<html>\r\n"
                + "<head>\r\n"
                + "<style>\r\n"
                + "\r\n"
                + "table,h3,h2,h4,i {\r\n"
                + "  font-family: arial, sans-serif;\r\n"
                + "  border-collapse: collapse;\r\n"
                + "  width: 60%;\r\n"
                + "  margin-left: auto; \r\n"
                + "  margin-right: auto;\r\n"
                + "}\r\n"
                + "\r\n"
                + "td {\r\n"
                + "  border: 1px solid grey;\r\n"
                + "  text-align: center;\r\n"
                + "  padding: 5px;\r\n"
                + "  background-color: LightBlue;\r\n"
                + "  \r\n"
                + "}\r\n"
                + "th {\r\n"
                + "  border: 1px solid gray;\r\n"
                + "  text-align: center;\r\n"
                + "  padding: 5px;\r\n"
                + "  background-color: CadetBlue;\r\n"
                + "}\r\n"
                + ".emailBody{\r\n"
                + "  border: 0px solid gray;\r\n"
                + "  padding: 80px;\r\n"
                + "  display: inline-block;\r\n"
                + "}\r\n"
                + ".summary{\r\n"
                + "  background-color: lightblue1;\r\n"
                + "  text-align: left;\r\n"
                + "  padding: 10px;\r\n"
                + "  width: 60%;\r\n"
                + "  margin-left: auto; \r\n"
                + "  margin-right: auto;\r\n"
                + "  max-width: 400px: \r\n"
                + "  display: inline-block;\r\n"
                + "}\r\n"
                + "\r\n"
                + "</style>\r\n"
                + "</head>\r\n"
                + "</body>\r\n"
                + "<div class='emailBody'>\r\n"
                + "<div class='summary'>\r\n"
                + "<h3>Summary</h3>\r\n"
                + "<p class='summaryText'> Automated text execution summary for <b><projectName></b> with below configuration and Test run is <b style='font-size:18;color:<runStatursColor>'><runStatus></b>."
                + "<br>\r\n"
                + "<label><b>Environment :</b> <environment></label><br>\r\n"
                + "<label><b>Tags :</b> <tags></label><br>\r\n"
                + "<label><b>Browser :</b> <browsrType></label><br>\r\n"
                + "</p>"
                + "<p><attachmentNote></p>\r\n"
                + "</p>\r\n"
                + "<h3>Execution Summary</h3>\r\n"
                + "<table>\r\n"
                + "<tr>\r\n"
                + "<th colspan = '4'>Features</th>\r\n"
                + "<th colspan = '3'>Scenarios</th>\r\n"
                + "</tr>\r\n"
                + "<tr>\r\n"
                + "<th style='color: green'>Passed</th>"
                + "<th style='color: FireBrick'>Failed</th>"
                + "<th style='color: GoldenRod'>Skipped</th>"
                + "<th>Total</th>\r\n"
                + "<th style='color: green'>Passed</th>"
                + "<th style='color: FireBrick'>Failed</th>"
                + "<th>Total</th>\r\n"
                + "</tr>\r\n"
                + "<td style='color: green'>FeaturesPassed</td>"
                + "<td style='color: FireBrick'>FeaturesFailed</td>"
                + "<td style='color: GoldenRod'>FeaturesSkipped</td>"
                + "<td>FeaturesTotal</td>\r\n"
                + "<td style='color: green'>ScenariosPassed</td>"
                + "<td style='color: FireBrick'>ScenariosFailed</td>"
                + "<td>ScenariosTotal</td>\r\n"
                + "</tr>\r\n"
                + "</table>\r\n"
                + "<br><br>\r\n"
                + "<a href='https://github.com/Mahi959/MyProjects'> Go to the project GIT repository"
                + "</div>\r\n"
                + "</div>\r\n"
                + "</body>\r\n"
                + "\r\n"
                +"</html>";
    }

}
