#SMTP Config
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=16a41a0501@gmail.com
mail.password=MahesH@Ap07
protocol=smtp
connectiontimeout=5000
timeout=5000
writetimeout=5000
from=16a41a0501@gmail.com
max_attachment_size_in_MB=5
to=maheswarareddy959@gmail.com
automation.repo.url=https://github.com/Mahi959/MyProjects
selenium.grid.node.url=
os=windows





