#SMTP Config
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.username=16a41a0501@gmail.com
mail.password=MahesH@Ap07
protocol=smtp
connectiontimeout=5000
timeout=5000
writetimeout=5000
from=16a41a0501@gmail.com
max_attachment_size_in_MB=5
to=maheswarareddy959@gmail.com
automation.repo.url=https://github.com/Mahi959/MyProjects
selenium.grid.node.url=
os=windows

#Swiggy
Swiggy_URL=https://partner.swiggy.com/login/
swiggy_restaurantID=6305190216
swiggy_password=Millet9009

#Zomato
Zomato_URL=https://www.zomato.com/partners/login
zomato_Username=3p@milletexpress.in
zomato_password=Millet9009





