#SMTP Config
host=
port=25
protocol=smtp
connectiontimeout=5000
timeout=5000
writetimeout=5000
from=16a41a0501@gmail.com
max_attachment_size_in_MB=5
to=maheswarareddy959@gmail.com
automation.repo.url=https://github.com/Mahi959/MyProjects
os=windows


